name: Test with tox

on:
  - pull_request

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.42.1-jammy
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "pypy-3.8"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions coveralls
      - name: Test with tox
        run: tox -p auto
        env:
          TOX_PARALLEL_NO_SPINNER: 1
